### ISSUE TITLE
error 429

### ISSUE THREAD

**Issue by lsk4205** [Widiskel/midas-RWA-bot#1]
![error](https://github.com/user-attachments/assets/06717544-f7b0-4754-9f52-b6f33a52f289)

**Comment by Widiskel** [comment]
if you run with so much account better use proxy

**Comment by lsk4852** [comment]
> if you run with so much account better use proxy

already i am using proxies. i am running 50 accs and 50 proxies

**Comment by Widiskel** [comment]
> > if you run with so much account better use proxy
> 
> already i am using proxies. i am running 50 accs and 50 proxies

so the problem its because midas now use cloudflare, its hard to bypass if you run on vps

**Comment by baztardengine** [comment]
knp ya om
![image_2024-09-12_053212351](https://github.com/user-attachments/assets/d805f193-27ec-4098-92d6-fe6c3c73fea5)

**Comment by lsk4205** [comment]
> > > if you run with so much account better use proxy
> > 
> > 
> > already i am using proxies. i am running 50 accs and 50 proxies
> 
> so the problem its because midas now use cloudflare, its hard to bypass if you run on vps

so i run in my desktop. but same

**Comment by izzyDab** [comment]
> > > if you run with so much account better use proxy
> > 
> > 
> > already i am using proxies. i am running 50 accs and 50 proxies
> 
> so the problem its because midas now use cloudflare, its hard to bypass if you run on vps

so, no solution for now to bypass cloudfare?

**Comment by sarqovik** [comment]
> > > > if you run with so much account better use proxy
> > > 
> > > 
> > > already i am using proxies. i am running 50 accs and 50 proxies
> > 
> > 
> > so the problem its because midas now use cloudflare, its hard to bypass if you run on vps
> 
> so, no solution for now to bypass cloudfare?

same problem sir

**Comment by Widiskel** [comment]
> > > > > if you run with so much account better use proxy
> > > > 
> > > > 
> > > > already i am using proxies. i am running 50 accs and 50 proxies
> > > 
> > > 
> > > so the problem its because midas now use cloudflare, its hard to bypass if you run on vps
> > 
> > 
> > so, no solution for now to bypass cloudfare?
> 
> same problem sir

Just run on your local, (before run) open game once so your ip wouldn't got block. after that run the bot with mass mode.

midas is tap tap game with limited tap, so you just need to run it daily
