### ISSUE TITLE
is the query method available?

### ISSUE THREAD

**Issue by yayangkasep** [Widiskel/midas-RWA-bot#3]
The session method or using login with OTP is very prone to being blocked

**Comment by Widiskel** [comment]
its available, just create account and choose query

the block its not because session or query its because of cloudflare. if you run it on vps it will very often to get blocked try use proxy.

**Comment by yayangkasep** [comment]
> its available, just create account and choose query
> 
> the block its not because session or query its because of cloudflare. if you run it on vps it will very often to get blocked try use proxy.

![image](https://github.com/user-attachments/assets/1831b5eb-b0b7-4dc2-8330-49dafc8b37aa)
Why does Cloudflare always block the login? I'm using **WSL.**

**Comment by Widiskel** [comment]
> > its available, just create account and choose query
> > the block its not because session or query its because of cloudflare. if you run it on vps it will very often to get blocked try use proxy.
> 
> ![image](https://private-user-images.githubusercontent.com/33832706/367614757-1831b5eb-b0b7-4dc2-8330-49dafc8b37aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NDgyMTMsIm5iZiI6MTcyNjU0NzkxMywicGF0aCI6Ii8zMzgzMjcwNi8zNjc2MTQ3NTctMTgzMWI1ZWItYjBiNy00ZGMyLTgzMzAtNDlkYWZjOGIzN2FhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDA0MzgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhNTVkNjVkNGJkYmI1OWQzMzIxYTY4M2Y2M2Q1YzdmZTQ0MmI2MmYwNjI1MjA0YmQ5MDY4ZjJkMGI4NGI5ZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VZh2u0Harb6lKSXbDjLj4fFbesqpi2fkBtu5E6H2Xm8) Why does Cloudflare always block the login? I'm using **WSL.**

its game security to avoid bot.

**Comment by yayangkasep** [comment]
> > > its available, just create account and choose query
> > > the block its not because session or query its because of cloudflare. if you run it on vps it will very often to get blocked try use proxy.
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/33832706/367614757-1831b5eb-b0b7-4dc2-8330-49dafc8b37aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NDgyMTMsIm5iZiI6MTcyNjU0NzkxMywicGF0aCI6Ii8zMzgzMjcwNi8zNjc2MTQ3NTctMTgzMWI1ZWItYjBiNy00ZGMyLTgzMzAtNDlkYWZjOGIzN2FhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDA0MzgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhNTVkNjVkNGJkYmI1OWQzMzIxYTY4M2Y2M2Q1YzdmZTQ0MmI2MmYwNjI1MjA0YmQ5MDY4ZjJkMGI4NGI5ZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VZh2u0Harb6lKSXbDjLj4fFbesqpi2fkBtu5E6H2Xm8) Why does Cloudflare always block the login? I'm using **WSL.**
> 
> its game security to avoid bot.

I can't see the picture you provided.
